version: '3.2'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
  pg_routing:
    image: postgresql_krls:latest
    build:
      context: .
      dockerfile: Dockerfile.pgrouting
    volumes:
      - .:/openstreetmap-carto
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGHOST=pg_routing
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
  geo_agent:
    image: geo_agent:v1
    build:
      context: .
      dockerfile: ./geo_agent/Dockerfile.geo_agent
    volumes:
      - .:/openstreetmap-carto
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/agent.py:/geo_agent/agent.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/config/example_config_with_infection.json:/geo_agent/config/example_config_with_infection.json
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/event.py:/geo_agent/event.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/tracker.py:/geo_agent/tracker.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/event_functions/event_init.py:/geo_agent/event_functions/event_init.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/main.py:/geo_agent/main.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/population_geo.py:/geo_agent/population_geo.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/data/barnet_points_100.csv:/geo_agent/data/barnet_points_100.csv
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/infection_functions/infect_init.py:/geo_agent/infection_functions/infect_init.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/infection.py:/geo_agent/infection.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/subpopulations.py:/geo_agent/subpopulations.py
      - /Users/kevinryan/Documents/City_DSI/population_movement_simulations/openstreetmap-carto/geo_agent/utils.py:/geo_agent/utils.py
    depends_on:
      - pg_routing
    environment:
      - PGHOST=pg_routing
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
  test:
    image: test:v1
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/openstreetmap-carto

volumes:
  agent_locations:
