name: geopy_copy
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - geoplot=0.4.0=py_1
  - pip:
    - attrs==20.1.0
    - botocore==1.14.13
    - certifi==2020.6.20
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.5.0
    - Cython==0.29.21
    - Fiona==1.8.13.post1
    - geographiclib==1.50
    - geopandas==0.8.1
    - geopy==2.0.0
    - jmespath==0.9.4
    - matplotlib==3.2.1
    - munch==2.5.0
    - numpy==1.19.1
    - overpy==0.4
    - pandas==1.1.1
    - psycopg2==2.8.5
    - pyasn1==0.4.8
    - pycairo==1.19.1
    - pyproj==2.6.1.post1
    - python-dateutil==2.8.1
    - pytz==2020.1
    - PyYAML==5.3.1
    - rsa==3.4.2
    - ruamel.yaml==0.16.12
    - ruamel.yaml.clib==0.2.2
    - s3transfer==0.3.3
    - scipy==1.5.2
    - Shapely==1.7.1
    - six==1.15.0
    - wrapt==1.11.2
